### ISSUE TITLE
Action fails when using ignore_build_states

### ISSUE THREAD

**Issue by espipj** [EnricoMi/download-buildkite-artifact-action#22]
When I set `ignore_build_states` with the `passed` value It automatically fails the step when the buildkite pipeline passes
Is there a workaround? My use case is just to report the Buildkite pipeline state PASS/FAIL.
![image](https://user-images.githubusercontent.com/12865914/220704795-0304bbcd-449a-4baf-b3ea-948e072c7171.png)

**Comment by EnricoMi** [comment]
So you do not want to download any files, you only want to wait for the build to finish and reflect the build state in the state of this action?

The success or failure of this action is not meant to reflect the build state, but merely if this action worked as expected.

While not downloading artifacts this is not the primary task of this action, you might get there as follows:
1. Set `IGNORE_JOB_STATES` to `"timed_out,failed,passed,new"`, this makes the action not download artifacts from jobs in those states, essentially any artifact. If there are no artifacts, you may even skip this step.
2. Assert the build state from the action output `build-state`, e.g. like in https://github.com/horovod/horovod/blob/master/.github/workflows/ci-results.yaml#L134-L141

**Comment by espipj** [comment]
Thanks this worked!
